version = 0.1

[default.deploy.parameters]
stack_name = "mabr8-sam-next-lambda-adaptor"
resolve_s3 = true
s3_prefix = "mabr8-sam-next-lambda-adaptor"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-west-2"
